
spring:
  datasource:
    url:
    password:
    username:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: update #update the schema with the given values.
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql


logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG #show parameter binding

mail:
  address:
    admin: admin@gmail.com