
spring:
  datasource:
    url: jdbc:mariadb://codestates-main.c2eyuthvn0kf.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: admin
    password: xodid12!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: update #update the schema with the given values.
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql


logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG #show parameter binding