spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/main004db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: update #update the schema with the given values.
    properties:
      hibernate:
        format_sql: false #To beautify or pretty print the SQL
        show_sql: false #show sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: baram2449@gmail.com
    password: plxlbhvgjmcnmdjf
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG #show parameter binding

image:
  path: C:\Users\윤상혁\Desktop\java project\projectImage

mail:
  address:
    admin: admin@gmail.com

jwt:
  key: 4FizXKCsqLU4lKXNtWLnyMBax57eVryor6zmf7wPUhF5SGc25Tk7VzKhm5KiPgj
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

cloud:
  aws:
    credentials.access-key:
    credentials.secret-key:
    s3.bucket: codestates-main-project-image
    region.static: ap-northeast-2
    stack.auto: false



