
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/main004db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    #      ddl-auto: update #update the schema with the given values.
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG #show parameter binding

image:
  path: sss

  jwt:
    key: ${JWT_SECRET_KEY}               # 민감한 정보는 시스템 환경 변수에서 로드한다.
    access-token-expiration-minutes: 30
    refresh-token-expiration-minutes: 420